services:
  grpc-server:
    image: grpc-ffmpeg-server:latest
    build:
      context: ../.. # Go up two directories to the project root
      dockerfile: docker/Dockerfile.server
    container_name: grpc_ffmpeg_server
    ports:
      - "50051:50051"  # gRPC
      - "8080:8080"    # /health and /metrics
    environment:
      - VALID_TOKEN=your_auth_token_here
      # To enable TLS:
      # - USE_SSL=true
      # - SSL_CERT_PATH=/certs/server.crt
      # - SSL_KEY_PATH=/certs/server.key
    volumes:
      - ./data:/app/data           # Example: Map local data directory to the container
      - ./certs:/certs             # SSL certificates if needed
    restart: always
