apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# The namespace Jellyfin runs in, so the workers can use its volumes
namespace: jellyfin

resources:
  - DaemonSet.yaml
  - service.yaml
