apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
metadata:
  name: kustomization.jellyfin.rffmpeg-worker
  namespace: flux-system

resources:
  - DaemonSet.yaml
  - service.yaml