apiVersion: v1
kind: Service
metadata:
  name: ffmpeg-workers
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/name: ffmpeg-worker
  type: ClusterIP