[package]
name = "grpc-ffmpeg-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.14.2", features = ["tls-ring"] } 
prost = "0.14.2"
tonic-prost = { version = "0.14.2" } 
anyhow = "1"
thiserror = "1.0"
clap = { version = "4.4", features = ["derive"] }

[build-dependencies]
tonic-prost-build = "0.14.2" # Match tonic version
