clone:
  git:
    image: harbor.crystalnet.org/dockerhub-proxy/woodpeckerci/plugin-git:2.6.0
    settings:
      partial: false
      depth: 1

steps:
  docker-build-release:
    image: woodpeckerci/plugin-docker-buildx:2.3.0
    settings:
      repo: harbor.crystalnet.org/library/ffmpeg-worker,ghcr.io/crystalnet-org/ffmpeg-worker
      logins:
      - registry: https://harbor.crystalnet.org/
        username: robot$library+woodpecker
        password:
          from_secret: harbor_token
      - registry: https://ghcr.io/
        username: psych0d0g
        password:
          from_secret: GITHUB_TOKEN
      registry: harbor.crystalnet.org
      auto_tag: true
      dockerfile: Dockerfile
      platforms: linux/amd64
      dry_run: false
when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: tag
