clone:
  git:
    image: harbor.crystalnet.org/dockerhub-proxy/woodpeckerci/plugin-git:2.6.0
    settings:
      partial: false
      depth: 1

steps:
  docker-build-dev:
    image: woodpeckerci/plugin-docker-buildx:2.2.1
    settings:
      debug: true
      repo: harbor.crystalnet.org/library/ffmpeg-worker
      logins:
      - registry: https://harbor.crystalnet.org/
        username: robot$library+woodpecker
        password:
          from_secret: harbor_token
      registry: harbor.crystalnet.org
      tags: dev
      dockerfile: Dockerfile
      platforms: linux/amd64
      dry_run: false
when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: push